config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    resources :products
    root 'store#index', as: 'store', via: :all
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Pragprog Books Online Store</title>
	<%= stylesheet_link_tag "application", media: "all",
	"data-turbolinks-track" => true %>
	<%= javascript_include_tag "application",
	"data-turbolinks-track" => true %>
	<%= csrf_meta_tag %>
</head>
<body class="<%= controller.controller_name %>">
	<div id="banner">
	  <%= form_tag store_path, class: 'locale' do %>
			<%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
			<%= submit_tag 'submit' %>
			<%= javascript_tag "$('.locale input').hide()" %>
		<% end %>
		<%= image_tag("http://files.meetup.com/1611353/ruby-logo-crop.png", width: '40px') %>
		<%= @page_title || t('.title') %>
	</div>
	<div id="columns">
		<div id="side">
			<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
					<%= render @cart %>
				<% end %>
			<% end %>
			<ul>
				<li><%= link_to t('.home'), :store %></li>
				<li><a href="#"><%= t('.questions') %></a></li>
				<li><a href="#"><%= t('.news') %></a></li>
				<li><a href="#"><%= t('.contact') %></a></li>

				<% if session[:user_id] %>
					<ul>
						<li><%= link_to 'Orders', orders_path %></li>
						<li><%= link_to 'Products', products_path %></li>
						<li><%= link_to 'Users', users_path %></li>
					</ul>
					<%= button_to 'Logout', logout_path, method: :delete %>
				<% end %>
			</ul>
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>